language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - node_modules
    - libs
before_install:
  - npm install -g npm
install:
  - npm install
sudo: false
